/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useGSAP } from "@gsap/react";
import gsap from "gsap";

export function Planet(props) {
  const shapePlanet = useRef(null);
  const sephereRef = useRef(null);
  const ringRef = useRef(null);
  const { nodes, materials } = useGLTF("/models//Planet.glb");

  useGSAP(() => {
    const tl = gsap.timeline();
    tl.from(
      shapePlanet.current.position,
      {
        y: 5,
        duration: 3,
        ease: "circ.inOut",
      },
      "<"
    );

    tl.from(
      sephereRef.current.rotation,
      {
        x: 0,
        y: Math.PI,
        z: -Math.PI,
        duration: 10,
        ease: "power1.inOut",
      },
      "<"
    );
    tl.from(
      ringRef.current.rotation,
      {
        x: 1,
        y: 1,
        z: 0,
        duration: 10,
        ease: "power1.inOut",
      },
      "<"
    );
  });
  return (
    <group ref={shapePlanet} {...props} dispose={null}>
      <group ref={sephereRef}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere.geometry}
          material={materials["Material.002"]}
          rotation={[0, 0, 0.741]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere2.geometry}
          material={materials["Material.001"]}
          position={[0.647, 1.03, -0.724]}
          rotation={[0, 0, 0.741]}
          scale={0.223}
        />
      </group>
      <mesh
        ref={ringRef}
        castShadow
        receiveShadow
        geometry={nodes.Ring.geometry}
        material={materials["Material.001"]}
        rotation={[-0.124, 0.123, -0.778]}
        scale={2}
      />
    </group>
  );
}

useGLTF.preload("/models//Planet.glb");
