/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from "react";
import { OrbitControls, useGLTF } from "@react-three/drei";
import { useGSAP } from "@gsap/react";
import gsap from "gsap";

export function Planet(props) {
  const shapePlanet = useRef(null);
  const sephereRef = useRef(null);
  const ringRef = useRef(null);
  const { nodes, materials } = useGLTF("/models/Planet.glb");

  useGSAP(() => {
    const tl = gsap.timeline();
    tl.from(
      shapePlanet.current.position,
      {
        y: 5,
        duration: 2.3,
        ease: "circ.inOut",
      },
      "<",
    );

    tl.from(
      sephereRef.current.rotation,
      {
        x: 0,
        y: Math.PI,
        z: -Math.PI,
        duration: 10,
        ease: "power1.inOut",
      },
      "<",
    );
    tl.from(
      ringRef.current.rotation,
      {
        x: 1,
        y: 0.3,
        z: 0,
        duration: 10,
        ease: "power1.inOut",
      },
      "<",
    );
  });
  return (
    <group ref={shapePlanet} {...props} dispose={null}>
      <group ref={sephereRef}>
        <mesh
          receiveShadow
          geometry={nodes.Sphere.geometry}
          material={materials.Material}
        />
        <mesh
          castShadow
          geometry={nodes.Sphere2.geometry}
          material={materials["Material.004"]}
          position={[0.647, 1.03, -0.724]}
          rotation={[0, 0, 0.741]}
          scale={0.229}
        />
      </group>
      <mesh
        ref={ringRef}
        castShadow
        receiveShadow
        geometry={nodes.Ring.geometry}
        material={materials["Material.003"]}
        rotation={[-0.134, 0.112, -0.691]}
        scale={1.182}
      />
    </group>
  );
}

useGLTF.preload("/models//Planet.glb");
